### ISSUE TITLE
argv

### ISSUE THREAD

**Issue by Opensourcecommunitydevelopment** [yyfrankyy/dns-over-http2#10]
how you set port and IP if subnet shall be empty? Because subnet is first Argument and if it is „empty“ port is interpreted As subnet And IP As port?
i don't get it. If i use with defaults Index.js its Fine. But if i Want Run subnet empty and port 53 i can't ?
How about changing this behaivior To something like -e "0.0.0.0/0" -p 53 -a 127.0.0.1 for example… for future config param like padding or additional resolver when first come

**Comment by yyfrankyy** [comment]
just some lazy and dirty implementation for now :-), let me use some arguments parsing tool to fix this.
