### ISSUE TITLE
chicken and egg Problem for forwardurl resolve while h2dns  (forwarder) used As System resolver 

### ISSUE THREAD

**Issue by Opensourcecommunitydevelopment** [yyfrankyy/dns-over-http2#27]
it tries to resolve dns.google.com and fails, because it can't itself As it is a forwarder only.

suggested solution step:
1. Put a hardcoded fallback IP for both ipv6 and Internet Protocol Version 4, bad because it is Not anycasted like 8.8.8.8. should be used for very earliest first Connection Agent only If No other Connection could be made. because you Want the nearset dns.google.com Server near you for latency reasons.
2. while we ping it already, use the result! Cache at least the Response of dns.google.com between restarts.
3. use fallback only, if No previous Cached ip is PresenIP

for spdy, comman Name is required for certificate Validation. simply use Ip only As Host Not work here As wanted.

**Comment by yyfrankyy** [comment]
I prefer to do nothing about it, let the parent DNS resolve`dns.google.com`. anybody using DNS over HTTP should aware of this.
