### ISSUE TITLE
How to locate the maxListener leak?

### ISSUE THREAD

**Issue by yyfrankyy** [yyfrankyy/dns-over-http2#6]
After long run for couple hours, all requests are not responding due to listeners are no longer be added.

**Comment by Opensourcecommunitydevelopment** [comment]
i see error 

```
(node:10360) Warning: Possible EventEmitter memory leak detected. 11 _connect listeners added. Use emitter.setMaxListeners() to increase limit
(node:14408) Warning: Possible EventEmitter memory leak detected. 11 _connect listeners added. Use emitter.setMaxListeners() to increase limit
```

while setMaxListeners(0) //unlimited

**Comment by yyfrankyy** [comment]
me too, still figuring how to find out which emitter is leaking.

**Comment by Opensourcecommunitydevelopment** [comment]
Hi i found it reproduceable, Start fresh instance. if Connection is Not built/ Block with Firewall. Than dig it 11 times After Agent complaining. To Get leak Warning ;-)

agent error: Error: connect ECONNREFUSED 216.58.208.142
(node:28352) Warning: Possible EventEmitter memory leak detected. 11 _connect listeners added. Use emitter.setMaxListeners() to increase limit
